### ISSUE TITLE
The go get module is different from the one on github

### ISSUE THREAD

**Issue by MuntherJaber** [r3labs/diff#39]
When I go get the module, lets say options.go is missing a few functions.

**Comment by purehyperbole** [comment]
Apologies, i forgot to tag a release last time i merged a PR. This should now be fixed.

**Comment by MuntherJaber** [comment]
Thank you!

**Comment by MuntherJaber** [comment]
Maybe I doing something wrong, but still the same.

**Comment by purehyperbole** [comment]
Does performing `go get github.com/r3labs/diff` in the root of your project folder change anything?

You may need to manually set the version constraint in your go.mod file if it doesn't pull down the latest for you.

**Comment by MuntherJaber** [comment]
Yes thank you, it did and now the problem seems to be go mod wont download a breaking version even after deleting the diff module, mod files, and running clean.

**Comment by MuntherJaber** [comment]
When I did I go the following:
require github.com/r3labs/diff: version "v2.4.0" invalid: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2

**Comment by purehyperbole** [comment]
@MuntherJaber @clok Very sorry for the long delay in resolving this! I have been unable to find the time due to other work commitments.

I've now created a v2 branch and setup the repo for go module support beyond v1. You should now be able to pull down v2 with a:

```sh
go get github.com/r3labs/diff/v2
```

You should then be able import in your application like:
```go
import (
    "github.com/r3labs/diff/v2"
)
```

Please let me know if there are any issues.

**Comment by MuntherJaber** [comment]
Thank you
